export const DEFAULT_SETTINGS = {
  LLM_MEM_MODEL: 'claude-sonnet-5',
  LLM_MEM_CONTEXT_OBSERVATIONS: '50',
  LLM_MEM_WORKER_PORT: '37700',
  LLM_MEM_WORKER_HOST: '127.0.0.1',

  LLM_MEM_PROVIDER: 'claude',
  LLM_MEM_GEMINI_API_KEY: '',
  LLM_MEM_GEMINI_MODEL: 'gemini-flash-latest',
  LLM_MEM_OPENROUTER_API_KEY: '',
  LLM_MEM_OPENROUTER_MODEL: 'xiaomi/mimo-v2-flash:free',
  LLM_MEM_OPENROUTER_SITE_URL: '',
  LLM_MEM_OPENROUTER_APP_NAME: 'llm-mem',
  LLM_MEM_GEMINI_RATE_LIMITING_ENABLED: 'true',

  LLM_MEM_CONTEXT_SHOW_READ_TOKENS: 'false',
  LLM_MEM_CONTEXT_SHOW_WORK_TOKENS: 'false',
  LLM_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: 'false',
  LLM_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  LLM_MEM_CONTEXT_FULL_COUNT: '0',
  LLM_MEM_CONTEXT_FULL_FIELD: 'narrative',
  LLM_MEM_CONTEXT_SESSION_COUNT: '10',

  LLM_MEM_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  LLM_MEM_CONTEXT_SHOW_LAST_MESSAGE: 'false',

  LLM_MEM_OLLAMA_URL: 'http://127.0.0.1:11434',
  LLM_MEM_VECTOR_EMBEDDING_MODEL: 'nomic-embed-text',
} as const;
